# Generated by Django 3.1.2 on 2020-10-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201019_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='ADMINISTRATOR', on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
