# Generated by Django 3.1.2 on 2020-10-19 10:12

from django.db import migrations

from users import roles, permissions


def create_permissions(apps, _):
    Permission = apps.get_model('users', 'Permission')
    Role = apps.get_model('users', 'Role')
    permission = Permission.objects.get(codename=permissions.CAN_CREATE_CLIENT_APPLICATION)

    role = Role.objects.get(codename=roles.ADMINISTRATOR['codename'])
    role.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20201019_1008'),
    ]

    operations = [
        migrations.RunPython(create_permissions)
    ]
