# Generated by Django 3.1.2 on 2020-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_employers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationclientapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('sent', 'Sent'), ('received', 'Received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('issued', 'Issued')], default='new', max_length=20),
        ),
    ]
